// Generated by CoffeeScript 1.9.1
(function() {
  var bodyParser, connect, data, launchServer, serveStatic, svrConfig;

  connect = require('connect');

  serveStatic = require('serve-static');

  bodyParser = require('body-parser');

  data = require('./data');

  data.dbConfig = {
    url: 'mongodb://localhost/test'
  };

  svrConfig = {
    port: 1337,
    host: 'localhost',
    rootDir: 'web'
  };

  launchServer = function() {
    var svr;
    svr = connect().use(serveStatic(svrConfig.rootDir)).use(bodyParser.urlencoded({
      extended: false
    })).use(bodyParser.json()).use('/data', data.connectHandler);
    svr.listen(svrConfig.port, svrConfig.host);
    return console.log("Server running at http://" + svrConfig.host + ":" + svrConfig.port + "/");
  };

  data.openDbConnection(function(err) {
    if (err) {
      return console.error('Could not connect to database', err);
    } else {
      return launchServer();
    }
  });

}).call(this);
